'use client'

import { useMemo, useState } from 'react'
import { ArrowRight, Check, ChevronRight, LocateFixed, MapPin, Mic, Phone, Search, ShieldCheck, Stethoscope } from 'lucide-react'

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || 'https://tifftxvaomcebmxqcwrc.supabase.co'
const SUPABASE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || 'sb_publishable_SDPzLK-wt5Pp1SGB0EjAoA_0t23wTv'

type Service={slug:string;name:string}
type Facility={id:string;name:string;facility_type:string;address:string;district:string;state:string;phone:string|null;latitude:number;longitude:number;confidence_score:number;verification_status:string;source_name:string|null;distance_km:number|null;services:Service[]}

const fallbackFacilities:Facility[]=[
 {id:'demo-1',name:'B. J. Government Medical College & Sassoon General Hospitals',facility_type:'Government Hospital',address:'Pune, Maharashtra',district:'Pune',state:'Maharashtra',phone:null,latitude:18.525329,longitude:73.870545,confidence_score:90,verification_status:'source_imported',source_name:'Public source',distance_km:null,services:[{slug:'tb-screening',name:'TB services'},{slug:'anc',name:'ANC'},{slug:'vaccination',name:'Vaccination'},{slug:'ncd',name:'Diabetes & BP'},{slug:'eye',name:'Eye care'},{slug:'dental',name:'Dental care'}]},
 {id:'demo-2',name:'Maharashtra Institute of Mental Health',facility_type:'Government Institute',address:'Pune, Maharashtra',district:'Pune',state:'Maharashtra',phone:null,latitude:18.526,longitude:73.8711,confidence_score:95,verification_status:'source_imported',source_name:'Government of Maharashtra',distance_km:null,services:[{slug:'mental-health',name:'Mental health'}]}
]

const needs=[
 ['🧭','Find care','Hospitals, PHCs & Arogya Mandirs',''],['🧪','Find a test','Diagnostics and screening','tb-screening'],['👶','Pregnancy & ANC','Care for mother and baby','anc'],['💉','Vaccination','Find immunisation services','vaccination'],['🫁','TB services','Testing, treatment & follow-up','tb-screening'],['🩺','Diabetes & BP','Screening and primary care','ncd'],['👁️','Eye care','Vision and basic eye services','eye'],['🦷','Dental care','Nearby public dental services','dental'],
] as const

async function searchFacilities(query:string,service:string,coords?:GeolocationCoordinates){
 const body:any={search_text:query||'',requested_service:service||'',result_limit:20};
 if(coords){body.user_lat=coords.latitude;body.user_lng=coords.longitude;body.radius_km=50}
 try{
  const res=await fetch(`${SUPABASE_URL}/rest/v1/rpc/search_facilities`,{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(body)});
  if(!res.ok) throw new Error('search failed');
  const data=await res.json();
  return data.length?data as Facility[]:fallbackFacilities;
 }catch{return fallbackFacilities.filter(f=>!service||f.services.some(s=>s.slug===service))}
}

export default function Home(){
 const[query,setQuery]=useState('');const[service,setService]=useState('');const[results,setResults]=useState<Facility[]>([]);const[loading,setLoading]=useState(false);const[location,setLocation]=useState(false);const[lang,setLang]=useState<'en'|'hi'|'mr'>('en');const[error,setError]=useState('');
 const copy=lang==='hi'?{ey:'सरकारी स्वास्थ्य सेवा, आसान तरीके से',title:'सही इलाज। आपके पास।',sub:'कहाँ जाना है, क्या पूछना है और कौन-सी सरकारी मदद मिल सकती है — बिना सिस्टम जाने समझें।',need:'आज आपको किस मदद की जरूरत है?',search:'जैसे “मुझे टीबी टेस्ट चाहिए” या “नजदीकी PHC”',benefit:'सरकारी योजनाएं खोजें',urgent:'तुरंत मदद चाहिए?',find:'खोजें',near:'मेरे पास खोजें'}:lang==='mr'?{ey:'सरकारी आरोग्यसेवा, सोप्या पद्धतीने',title:'योग्य उपचार. तुमच्या जवळ.',sub:'कुठे जायचे, काय विचारायचे आणि कोणती सरकारी मदत मिळू शकते — प्रणाली माहित नसली तरी समजा.',need:'आज तुम्हाला कशाची गरज आहे?',search:'उदा. “मला TB चाचणी हवी” किंवा “जवळचे PHC”',benefit:'सरकारी योजना शोधा',urgent:'तातडीची मदत हवी?',find:'शोधा',near:'माझ्याजवळ शोधा'}:{ey:'PUBLIC HEALTHCARE, MADE SIMPLE',title:'Find the right care. Near you.',sub:"Go Health helps you understand where to go, what to ask for, and which government benefit may help — without needing to know the system first.",need:'What do you need today?',search:'Try “I need a TB test” or “nearest PHC”',benefit:'Find government benefits',urgent:'Need urgent care?',find:'Search',near:'Find near me'};
 const runSearch=async(q=query,s=service,coords?:GeolocationCoordinates)=>{setLoading(true);setError('');try{setResults(await searchFacilities(q,s,coords))}catch{setError('Care search is temporarily unavailable. Please try again.')}finally{setLoading(false)}};
 const choose=(title:string,slug:string)=>{setQuery(title);setService(slug);void runSearch(title,slug)};
 const detect=()=>{if(!navigator.geolocation)return void runSearch();navigator.geolocation.getCurrentPosition(p=>{setLocation(true);void runSearch(query,service,p.coords)},()=>void runSearch())};
 const suggestions=useMemo(()=>query.trim()?needs.filter(n=>`${n[1]} ${n[2]}`.toLowerCase().includes(query.toLowerCase())).slice(0,4):[],[query]);
 return <main className="shell">
 <header className="topbar"><div className="logo"><span className="logo-mark">+</span><span>Go Health</span></div><div className="top-actions"><button type="button" className="lang" onClick={()=>setLang(lang==='en'?'hi':lang==='hi'?'mr':'en')}>{lang==='en'?'हिन्दी / मराठी':lang==='hi'?'मराठी / English':'English / हिन्दी'}</button><button type="button" className="loc-top" onClick={detect}><LocateFixed size={16}/>{location?'Location on':'Use location'}</button></div></header>
 <section className="hero"><div><div className="eyebrow">{copy.ey}</div><h1>{copy.title}</h1><p>{copy.sub}</p><form className="search" onSubmit={e=>{e.preventDefault();void runSearch()}}><Search size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search healthcare" placeholder={copy.search}/><button type="submit">{copy.find}<ArrowRight size={17}/></button></form><div className="voice-row"><button type="button" className="ghost" onClick={detect}><MapPin size={17}/>{copy.near}</button><button type="button" className="ghost" onClick={()=>setError('Voice search will be enabled in the next release. You can type your need in everyday language today.')}><Mic size={17}/>Speak your need</button></div>{suggestions.length>0&&<div className="suggestions">{suggestions.map(n=><button type="button" key={n[1]} onClick={()=>choose(n[1],n[3])}>{n[0]} {n[1]}<ChevronRight size={16}/></button>)}</div>}</div><div className="hero-card"><div className="pill"><ShieldCheck size={15}/> Navigation, not diagnosis</div><div className="big">Know what to do next.</div><p>Find an appropriate facility, understand the service, check possible benefits, and get directions.</p><div className="trust"><span className="pill">✓ Source-aware</span><span className="pill">✓ Plain language</span><span className="pill">✓ Built for India</span></div></div></section>
 <section className="section"><div className="section-head"><div><h2>{copy.need}</h2><p>Start with the service you need. You do not need to know whether it is a PHC, CHC or hospital.</p></div><Stethoscope size={28}/></div><div className="grid">{needs.map(([i,t,d,s])=><button type="button" className="tile" key={t} onClick={()=>choose(t,s)}><div className="icon">{i}</div><strong>{t}</strong><span>{d}</span><ChevronRight className="tile-arrow" size={18}/></button>)}</div></section>
 {loading&&<section className="results"><div className="loading"><span className="spinner"/>Finding appropriate public care…</div></section>}{error&&<section className="results"><div className="notice">{error}</div></section>}
 {!loading&&results.length>0&&<section className="results"><div className="results-head"><div><div className="eyebrow">YOUR NEXT BEST OPTIONS</div><h2>{results.length} care options</h2></div><button type="button" className="ghost" onClick={()=>{setResults([]);setQuery('');setService('')}}>Clear</button></div>{results.map(r=><article className="facility" key={r.id}><div className="facility-main"><div className="facility-icon">🏥</div><div><div className="facility-type">{r.facility_type}</div><h3>{r.name}</h3><p>{r.address||r.district||'Location details being verified'}</p><div className="chips"><span className="confidence"><Check size={14}/> {r.confidence_score}% source confidence</span>{r.distance_km!==null&&<span>{r.distance_km} km away</span>}{r.services?.slice(0,4).map(s=><span key={s.slug}>{s.name}</span>)}</div></div></div><div className="facility-actions">{r.phone&&<a href={`tel:${r.phone}`}><Phone size={16}/> Call</a>}<a target="_blank" rel="noreferrer" href={`https://www.google.com/maps/dir/?api=1&destination=${r.latitude},${r.longitude}`}><MapPin size={16}/> Directions</a></div></article>)}</section>}
 {!results.length&&!loading&&<section className="section cards"><div className="benefit-card"><div className="icon">💰</div><h3>{copy.benefit}</h3><p>Explore central and state health schemes. We show possible matches and always direct you to the official source for final eligibility.</p><a href="/schemes" className="cta">Explore schemes <ArrowRight size={16}/></a></div><div className="benefit-card urgent"><div className="icon">🚨</div><h3>{copy.urgent}</h3><p>If this is an emergency, seek immediate local emergency help.</p><button type="button" className="cta" onClick={()=>void runSearch('Emergency','')}>Find emergency care <ArrowRight size={16}/></button></div></section>}
 <footer className="footer"><div><strong>Go Health</strong><br/>Your guide to India's public healthcare.</div><p>Go Health is a navigation service. It does not diagnose, prescribe, or replace a qualified healthcare professional. Facility availability and scheme eligibility must be confirmed with the facility or official source.</p><div className="footer-links"><a href="https://aam.mohfw.gov.in/" target="_blank" rel="noreferrer">AAM</a><a href="https://nha.gov.in/" target="_blank" rel="noreferrer">NHA / PM-JAY</a><a href="https://medical.maharashtra.gov.in/" target="_blank" rel="noreferrer">Maharashtra Health</a></div></footer></main>
}
