import Link from 'next/link'
import { ArrowRight, ExternalLink, ShieldCheck } from 'lucide-react'

const capabilities=[
 ['🧪','Laboratory services','3,502 institutions are reported under the Maharashtra public laboratory network.','https://nhm.maharashtra.gov.in/en/scheme/iphs-2/'],
 ['🩻','CT & MRI','Maharashtra NHM publishes facility-level information for CT and MRI programmes.','https://nhm.maharashtra.gov.in/en/scheme/iphs-2/'],
 ['🦷','Dental care','The state reports 288 functional dental clinics across public facilities.','https://nhm.maharashtra.gov.in/en/scheme/national-oral-health-program/'],
 ['🌿','AYUSH','The state reports 647 AYUSH facilities in published programme data.','https://nhm.maharashtra.gov.in/en/scheme/ayush-national-ayush-mission/'],
 ['❤️','Heart attack pathway','The STEMI programme connects PHCs and higher facilities through a hub-and-spoke emergency pathway.','https://nhm.maharashtra.gov.in/en/scheme/national-program-for-prevention-and-control-of-non-communicable-diseases-np-ncd/'],
 ['👴','Elderly care','Public elderly-care pathways connect primary care to referral facilities.','https://nhm.maharashtra.gov.in/en/scheme/national-programme-for-health-care-of-the-elderly-nphce/'],
 ['🤍','Palliative care','Public palliative-care pathways combine hospital, community and home-based care.','https://nhm.maharashtra.gov.in/en/scheme/national-program-for-palliative-care-nppc/'],
 ['🫁','TB & screening','Government programmes provide screening, referral and treatment pathways.','https://nhm.maharashtra.gov.in/'],
]
const actions=['Tell us what you need','Find the right care level','Match service capability','Show evidence & freshness','Explain what to ask next']
export default function Intelligence(){return <main className="shell"><header className="topbar"><Link className="logo" href="/" style={{textDecoration:'none',color:'inherit'}}><span className="logo-mark">+</span><span>Go Health</span></Link><Link href="/" className="ghost">← Find care</Link></header><section className="intel-hero"><div className="eyebrow">HEALTHCARE INTELLIGENCE</div><h1>Not a hospital directory. A guide to what the system can actually do.</h1><p>Go Health combines public programme evidence with facility data so citizens can move from a need to a realistic next step.</p><div className="intel-note"><ShieldCheck size={18}/><span>Sources are shown transparently. Programme evidence does not guarantee that a service is available today; confirm before travelling.</span></div></section><section className="action-grid">{actions.map((a,i)=><div key={a}><b>{String(i+1).padStart(2,'0')}</b><span>{a}</span></div>)}</section><h2>Public capability evidence</h2><p className="muted">These public programme signals become capability evidence that can be attached to facilities as our real-facility dataset expands.</p><section className="cap-grid">{capabilities.map(([icon,title,desc,url])=><article className="cap-card" key={title}><div className="cap-icon">{icon}</div><div className="eyebrow">{title.toUpperCase()}</div><p>{desc}</p><a href={url} target="_blank" rel="noreferrer">View source <ExternalLink size={14}/></a></article>)}</section><section className="path-card"><div><div className="eyebrow">THE GO HEALTH DIFFERENCE</div><h2>Need → right level → capability → evidence → action</h2><p>A facility is useful because it can deliver the service a citizen needs — not simply because it appears on a map.</p></div><Link href="/" className="cta">Find care <ArrowRight size={16}/></Link></section></main>}
