const capabilities = [
  {title:'CT Scan',count:'31+ SDH / 20 DH entries published',text:'Government Maharashtra NHM publishes named facilities with CT capability, including SDHs and District Hospitals. Go Health treats this as service evidence, not a generic hospital tag.',source:'https://nhm.maharashtra.gov.in/en/scheme/iphs-2/'},
  {title:'MRI',count:'22 District Hospitals in the state programme',text:'MRI is being provided through the state programme, with the published source identifying participating district hospitals and 24×7 project availability.',source:'https://nhm.maharashtra.gov.in/en/scheme/iphs-2/'},
  {title:'Laboratory services',count:'3,502 institutions covered',text:'The Maharashtra NHM laboratory programme reports coverage across HBT AD, UHWC, UPHC, PHC, rural/higher facilities. This becomes a service-capability layer rather than a hospital list.',source:'https://nhm.maharashtra.gov.in/en/scheme/iphs-2/'},
  {title:'Dental care',count:'288 functional dental clinics reported',text:'NHM Maharashtra publishes the distribution of functional dental clinics across district, general, sub-district, rural and women hospitals.',source:'https://nhm.maharashtra.gov.in/en/scheme/national-oral-health-program/'},
  {title:'AYUSH',count:'647 facilities reported for 2023–24',text:'The state AYUSH programme reports facilities across district hospitals, sub-district/rural hospitals and Ayushman Arogya Mandirs.',source:'https://nhm.maharashtra.gov.in/en/scheme/ayush-national-ayush-mission/'},
  {title:'NCD / STEMI',count:'2,126 facilities in expansion plan',text:'The state NCD programme describes a hub-and-spoke emergency cardiac pathway and expansion involving 1,906 PHCs plus higher-level facilities.',source:'https://nhm.maharashtra.gov.in/en/scheme/national-program-for-prevention-and-control-of-non-communicable-diseases-np-ncd/'},
  {title:'Elderly care',count:'PHC → CHC → District Hospital',text:'The state elderly-care programme defines weekly geriatric clinics at PHCs, first-referral services at CHCs and dedicated district-hospital services.',source:'https://nhm.maharashtra.gov.in/en/scheme/national-programme-for-health-care-of-the-elderly-nphce/'},
  {title:'Palliative care',count:'Community + hospital pathway',text:'The programme connects district OPD/IPD services with outreach at CHC/PHC/HWC level and home-based care.',source:'https://nhm.maharashtra.gov.in/en/scheme/national-program-for-palliative-care-nppc/'},
]
const actions=['Find the right facility','Check service capability','Understand the referral path','Know what to ask for','Find possible government support']
export default function Intelligence(){return <main style={{maxWidth:1120,margin:'0 auto',padding:'28px 20px',fontFamily:'system-ui',color:'#12322b'}}><header style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:20,marginBottom:45}}><a href="/" style={{textDecoration:'none',color:'#087c67',fontWeight:800}}>← Go Health</a><span style={{fontSize:12,letterSpacing:'.12em',fontWeight:800,color:'#087c67'}}>HEALTHCARE INTELLIGENCE</span></header><section style={{maxWidth:780,marginBottom:38}}><div style={{fontSize:13,fontWeight:800,color:'#087c67'}}>NOT A HOSPITAL DIRECTORY</div><h1 style={{fontSize:'clamp(40px,7vw,72px)',lineHeight:.98,letterSpacing:'-.05em',margin:'10px 0 20px'}}>Know what the system can actually do.</h1><p style={{fontSize:18,lineHeight:1.65,color:'#64736f'}}>Go Health combines public programme information with facility data so a citizen can move from a need to a realistic next step — not just a map pin.</p></section><section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:12,marginBottom:45}}>{actions.map((a,i)=><div key={a} style={{background:'#e8f7f2',border:'1px solid #cdebe2',borderRadius:18,padding:17}}><strong>{String(i+1).padStart(2,'0')}</strong><div style={{marginTop:12,fontWeight:700}}>{a}</div></div>)}</section><h2 style={{fontSize:30,letterSpacing:'-.03em'}}>Public capability evidence</h2><p style={{color:'#64736f'}}>These are source-attributed programme signals we can attach to individual facilities as the facility ingestion layer is expanded.</p><section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:15,marginTop:18}}>{capabilities.map(c=><article key={c.title} style={{background:'#fff',border:'1px solid #dce9e5',borderRadius:22,padding:21,boxShadow:'0 8px 30px rgba(18,50,43,.05)'}}><div style={{fontSize:12,fontWeight:800,color:'#087c67',letterSpacing:'.08em'}}>{c.title.toUpperCase()}</div><h3 style={{fontSize:24,margin:'8px 0'}}>{c.count}</h3><p style={{color:'#64736f',lineHeight:1.55,fontSize:14}}>{c.text}</p><a href={c.source} target="_blank" rel="noreferrer" style={{fontSize:12,color:'#087c67',fontWeight:700}}>View source →</a></article>)}</section><section style={{marginTop:45,background:'#12322b',color:'#fff',borderRadius:25,padding:27}}><h2 style={{marginTop:0}}>The Go Health difference</h2><p style={{color:'#c9d8d4',lineHeight:1.7}}>A facility is not useful because it exists. It is useful because it can deliver the service the citizen needs. Our data model therefore separates facilities from capabilities, programme evidence, referral pathways and source confidence.</p></section></main>}
